version: 2.1
jobs:
  build:
    docker:
      - image: dnsl48/silverstripe-php71-cli:latest
      - image: circleci/mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: the_database
          MYSQL_HOST: '127.0.0.1'

    steps:
      - checkout

      # Configure PHP

      # - run:
      #     name: configure php.ini
      #     command: |
      #       cat << EOF > /usr/local/etc/php/php.ini
      #       memory_limit=2G
      #       date.timezone=Pacific/Auckland
      #       EOF


      # Composer Install

      - restore_cache:
          keys:
            - composer-cache-{{ .Branch }}

      - run: composer validate
      - run: composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

      - save_cache:
          key: composer-cache-{{ .Branch }}
          paths:
            - ~/.composer/cache

      - run: vendor/bin/phpunit --testsuite mfa --exclude-group exclude-from-travis;

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date