version: 2.1
jobs:
  build:
    docker:
      - image: dnsl48/silverstripe-php71-cli:latest
      - image: circleci/mysql:5.6

    steps:
      - checkout

      # Composer Install

      - run: composer validate
      - run: composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date