version: 2.1
jobs:
  build:
    docker:
      - image: dnsl48/silverstripe-php71-cli:latest
      - image: circleci/mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: the_database
          MYSQL_HOST: '127.0.0.1'

    steps:
      - checkout

      # Composer Install

      - run: composer validate

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}

      - run: composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      - run: vendor/bin/phpunit --testsuite "$PHPUNIT_TEST" --exclude-group exclude-from-travis;

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date