version: 2.1
jobs:
  build:
    docker:
      - image: dnsl48/silverstripe-php71-cli:latest
      - image: circleci/mysql:5.6
        environment:
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: the_database
          MYSQL_HOST: '127.0.0.1'

    steps:
      - checkout

      # Composer Install

      - restore_cache:
          keys:
            - composer-cache

      - run: composer validate
      - run: composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile

      - save_cache:
          key: composer-cache
          paths:
            - ~/.cache/.composer/cache/

      - run: vendor/bin/phpunit --testsuite mfa --exclude-group exclude-from-travis;

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date