version: 2.1

description: Testing the Orbs


orbs:
  core: dnsl48/silverstripe-core@dev:unua


workflows:
  version: 2
  build:
    jobs:
      - core/unit-suite-with-mysql:
          php: "71"
          suite: mfa

      - core/unit-suite-with-mysql:
          php: "72"
          suite: mfa
